Домашнее задание 1
ruslanbk11/2018-FS-11-Frontend-Koshkin pull request #1
Opened 2018-10-10 20:06 UTC by ruslanbk11

-- Изменил функцию say так, чтобы сообщение появлялось на странице в блоке цвета отличного, от цвета страницы
-- Прогнал файлы через eslint

2018-10-10 20:18 UTC, ruslanbk11 commented
Как-то по-дурацки получилось, не знал, зачем нужен этот пулреквест и сразу все закоммитил в мастер, извините ))) В следующий раз исправлюсь

2018-10-11 21:37 UTC, martinkomitsky requested changes

2018-10-11 21:37 UTC, martinkomitsky commented on .gitignore
> +*.swo
dist сюда же, саму папку удалить из репы

2018-10-11 21:37 UTC, martinkomitsky commented on static/styles.css
> +div.block {
Достаточно написать просто `block`. Текущая запись избыточна

2018-10-11 21:37 UTC, martinkomitsky commented
Исправить замечания @ruslanbk11

2018-10-12 06:34 UTC, ruslanbk11 commented
@martinkomitsky, почему-то если я просто пишу block в css, то стили не применяются, написал с точкой и все хорошо. Это ведь наверно так и должно быть ?)

2018-10-12 11:46 UTC, martinkomitsky commented
@ruslanbk11 именно, я имел ввиду, что не обязательно писать `div.className`, можно просто `.className`

2018-10-12 11:47 UTC, martinkomitsky approved these changes

2018-10-12 11:47 UTC, merged

2018-10-12 11:47 UTC, martinkomitsky commented
10

2018-10-12 11:48 UTC, martinkomitsky commented
@ruslanbk11 только этот пулл реквест должен был быть в мастер, создай еще один и кинь теперь в мастер и на меня