Sem2hw4
ruslanbk11/2018-FS-11-Frontend-Koshkin pull request #6
Opened 2019-04-04 16:09 UTC by ruslanbk11

Добавил CSS Modules
На странице авторизации кнопочка меняет цвет при наведении
В списке сообщений сообщения добавляются с анимацией
Клавиатура эмоджи пульсирует при наведении (сама она пока не работает)
Ну и там еще viewport есть

2019-04-05 19:04 UTC, ruslanbk11 commented
Чтобы залогиниться, введи, пожалуйста, в local storage переменную access_token с любым значением через инструменты разработчика )

2019-04-06 11:11 UTC, martinkomitsky commented on src/components/EmojiBar/EmojiBar.css
> +@-webkit-keyframes pulse {
Все вендорные префиксы из css надо удалить. Для этого у вас уже есть автопрефиксер в проекте установлен

2019-04-06 11:23 UTC, martinkomitsky requested changes
Вроде бы все ок. Но картинки не показываются в списке сообщений.
![image](https://user-images.githubusercontent.com/14847018/55668824-7a6fa380-5877-11e9-929e-98d8daccda73.png)
Выбор эмоджиков - фееричный)

2019-04-06 15:50 UTC, ruslanbk11 commented
С картинками у меня проблемы, я не очень понимаю, как мне их из спрайта достать. Я думал по клику мыши просто забирать свойство background у эмоджи, на которую кликнул, брал оттуда url, но так не сработало.

2019-04-06 18:07 UTC, martinkomitsky commented
> Я думал по клику мыши просто забирать свойство background у эмоджи, на которую кликнул, брал оттуда url, но так не сработало.

Зачем? Ты же по клику знаешь какой emoji был нажат. Собственно, можешь в этот момент передать в компонент информацию о коде emoji, который был показан и просто отобразить картинку с классом, у которого бекграунд выставлен.

2019-04-06 19:39 UTC, martinkomitsky commented
@ruslanbk11 я еще у тебя нашел ветку с дз7 с того сема. Похоже, что там какие-то важные правки, может, доделаешь?
https://github.com/ruslanbk11/2018-FS-11-Frontend-Koshkin/compare/hw7?expand=1

2019-04-07 20:45 UTC, ruslanbk11 commented
Там в hw7 была авторизация, я ее Олегу сдал в зачет, а пулреквест не сделал тогда, думал уже смысла нет. Так что там вроде все доделано, а коммиты той ветки в этой тоже есть.

2019-04-08 19:38 UTC, martinkomitsky approved these changes

2019-04-08 19:39 UTC, martinkomitsky approved these changes

2019-04-08 19:39 UTC, merged

2019-04-08 19:39 UTC, martinkomitsky commented
повезло, так как сдал в последний день срока.
10 + бонус

2019-04-08 19:43 UTC, martinkomitsky commented
> коммиты той ветки в этой тоже есть.

Действительно, так. 

Хмм, а в этой ветке еще ж и дз 1 сделано, судя по всему