Sem2hw6
ruslanbk11/2018-FS-11-Frontend-Koshkin pull request #8
Opened 2019-04-18 17:39 UTC by ruslanbk11

Переписал компонент Message
Добавил компонент Аватар, в нем использовал хук
Старых компонентов жизненного цикла нет

2019-04-18 18:26 UTC, chexex commented on src/components/Avatar/index.js
> +export const Avatar = () => {
Почему бы не `export default () => {...` ?

2019-04-18 18:26 UTC, chexex commented on src/components/Avatar/index.js
> +            {zoomed && <div>{ReactDOM.createPortal(shadowElement, document.body)}</div>}
Чуть красивше:
```js
{
  zoomed &&
  <div>{ReactDOM.createPortal(shadowElement, document.body)}</div>
}
```

2019-04-18 18:26 UTC, chexex commented on src/components/Avatar/index.js
> +            <img onClick={() => setZoomed(!zoomed)} alt="noav" src={avatar} className={zoomed ? styles.zoomed : styles.not_zoomed}></img>
Чем короче строка, тем удобнее читать/ревьюить/сравнивать
```js
<img 
  onClick={() => setZoomed(!zoomed)}
  alt="noav"
  src={avatar}
  className={zoomed ? styles.zoomed : styles.not_zoomed}>
</img>
```

2019-04-18 18:26 UTC, chexex commented on src/components/ChatList/index.js
>      for(let i = 0; i < this.props.chats.length; i++){
Заменить на `map`, пожалуйста.
SomeArray.map(el => (...jsx...))

2019-04-18 18:26 UTC, chexex commented on src/store/reducer.js
>      newChats[0].last_message_content = payload.text;
```js
let newChat = newChats[0]
newChat.someAttr = 'some value'
...
newChats[0] = newChat
```

2019-04-18 18:26 UTC, chexex commented on src/components/Message/index.js
> +  const message = props.message
`const { message } = props`

2019-04-18 18:26 UTC, chexex commented on src/components/Message/index.js
> +  const author = isMy || <section className='author'>{message.author}</section>
Бизнес логику советую сопровождать комментариями и писать максимально наглядно:
```js
let author;
# Если сообщение не принадлежит пользователю,
# то отобразить элемент с автором сообщения
if (!isMy) {
  author = <section className='author'>{message.author}</section>
}
```

2019-04-18 19:51 UTC, ruslanbk11 commented on src/store/reducer.js
>      newChats[0].last_message_content = payload.text;
Но мне очень сильно хотелось спред ( Прямо надо убрать обязательно?

2019-04-18 20:04 UTC, ruslanbk11 commented
7 домашку добавил в эту же ветку

2019-04-19 03:20 UTC, martinkomitsky reviewed
> 7 домашку добавил в эту же ветку

(((((((((((

2019-04-19 03:20 UTC, martinkomitsky commented on src/components/Avatar/index.js
> +    const shadowStyle = {
А почему стиль не в `.css`?

2019-04-19 05:46 UTC, chexex commented on src/store/reducer.js
>      newChats[0].last_message_content = payload.text;
Спред ведь никуда не девается :)

2019-04-19 06:45 UTC, ruslanbk11 commented on src/components/Avatar/index.js
> +    const shadowStyle = {
Сначала писал в css файле, но там как-то все очень криво было, подглядел такой вот вариант. Исправлю

2019-04-19 15:32 UTC, martinkomitsky requested changes
Исправить замечания

2019-04-19 18:10 UTC, ruslanbk11 commented
Я ведь вроде все исправил

2019-04-24 09:49 UTC, martinkomitsky commented
ДЗ6 - ок. Но я тут нашел и 7, почему-то

2019-04-24 09:51 UTC, martinkomitsky commented on src/utils/getReadableSize.js
> +module.exports = getReadableSize;
![image](https://user-images.githubusercontent.com/14847018/56650378-8fc63980-668f-11e9-8ec6-365bcd4734af.png)
Передал твоей функции `-1`, а она вернула это. Сделай, чтобы возвращала `false` + надо написать тест, который покрывает этот кейс

2019-04-24 09:52 UTC, martinkomitsky commented on src/utils/getReadableSize.js
> +        let vals = ['B', 'kB', 'MB', 'GB', 'TB'];
Для начала, `vals` - это константа. И она свободно может быть вынесена выше

2019-04-24 09:52 UTC, martinkomitsky commented on src/utils/getReadableSize.js
> +        let index = Math.floor( Math.log(size) / Math.log(1024) );
`index` – тоже константа, вроде ниже не меняется

2019-04-24 09:53 UTC, martinkomitsky commented on src/utils/getReadableSize.js
> +        return ( (size / 1024).toFixed(3).toString()  + ' ' + vals[index]);
Ну а это вполне себе `template string`. Вспоминаем дз5)

2019-04-24 09:53 UTC, martinkomitsky commented on src/utils/getReadableSize.test.js
> +  test("is 5555 a 1 kb??? I don't think so", () => {
Ну и определиться с типом кавычек. Тоже от дз5

2019-04-24 09:55 UTC, martinkomitsky commented on src/utils/getReadableSize.test.js
> +  test('i think it can not be object', () => {
лучше писать утвердительные и понятные выражения, например, "возвращает объект" или "результат функции !== объект" и т.д.

2019-04-24 09:56 UTC, martinkomitsky commented
> Я ведь вроде все исправил

дописал комменты по дз7

2019-04-28 16:54 UTC, martinkomitsky approved these changes

2019-04-28 16:54 UTC, merged

2019-04-28 16:54 UTC, martinkomitsky commented
макс за все